-- AlterTable
ALTER TABLE `nota_credito` ADD COLUMN `estado` ENUM('DISPONIBLE', 'PARCIAL', 'USADA', 'ANULADA') NOT NULL DEFAULT 'DISPONIBLE',
    ADD COLUMN `montoUsado` DECIMAL(10, 2) NOT NULL DEFAULT 0;
